### ISSUE TITLE
VSScopy

### ISSUE THREAD

**Issue by mojoba** [cregx/wim-backup#1]
Great tool! I have a workflow which uses VSScopy to backup the running system. I can restore by booting into Windows Recovery and pointing to the backup folder.

```
wbadmin start backup -allcritical -backuptarget:\\nas\server-backup -vssCopy -quiet
```

How does WIM backup solution compare to VSScopy? Is it more suitable for offline backup where the host OS is not running?

**Comment by cregx** [comment]
Thanks.

I'm not really familiar with VSScopy, so I can't make a relevant comparison between the two solutions.

However, WIM-Backup is indeed **designed for offline backups** (originally in the Windows client environment). 
When attempting an online backup in the server environment, e.g. Windows Server 2019 errors occur and no backup is created.
I am able to backup and also restore the server after shutdown and boot via WinPE without any issues. I hope this information helps you.
