### ISSUE TITLE
No compied version?

### ISSUE THREAD

**Issue by palentir** [cregx/wim-backup#5]
I can't see the EXE where this is compiled. I'd like to download it if possible?

**Comment by palentir** [comment]
Sorry Im blind, its in the small print on the right hand side.
e.g. https://github.com/cregx/wim-backup/releases/tag/v.1.1.4

**Comment by cregx** [comment]
Hello @palentir,

that's no problem.
If you have any questions or need help, just get in touch.
Best regards
