### ISSUE TITLE
Imaging Windows 24h2

### ISSUE THREAD

**Issue by drsure** [cregx/wim-backup#8]
Freshly installed Windows 24h2 booted Wim-Backup with new created image and the newest ADK. 

in GUI i cannot see the partitions to backup. 

with diskpart i can see the disk an the partitions. 

same hardware with windows 23h2 works fine.

**Comment by cregx** [comment]
Hi, I haven’t had the chance to test Windows 24H2 yet; it's still on my to-do list. However, I suspect the issue might be similar to what I’ve encountered with **Windows Server 2022**. Please take a look at this solution: [Use on Windows Server 2022 environment](https://github.com/cregx/wim-backup/wiki/Using-the-WIM-Backup#use-on-windows-server-2022-environment) and let me know if it resolves the problem.

**Comment by drsure** [comment]
resolved the problem :) thanks

**Comment by cregx** [comment]
You're welcome. Great to hear that it resolved the issue!
